<?php
/**
 * @author      Rizki Pratama @ciptaloka.com
 * @copyright   Copyright (c) 2017 Ciptaloka (http://ciptaloka.com)
 * @package     Ciptaloka_HelloWorld
 *
 * @var $this \Ciptaloka\HelloWorld\Block\Catalog\Product\HelloWorld
 */
?>
<div class="ciptaloka-helloworld-block" style="text-align: <?= $this->getTextAlign(); ?>;">
    <p><?= $this->getHelloWorldTxt() . " - <b>" . $this->getBlockLabel() . "</b>"; ?></p>
    <code><?php print_r($this->getCollection()); ?></code>
</div>
